In [26]:
from sklearn.datasets import load_iris
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
import numpy as np

In [27]:
iris = load_iris()

In [28]:
skf = StratifiedKFold(shuffle=True, n_splits=4)

In [29]:
from sklearn import metrics
lr = cross_val_score(LogisticRegression(max_iter=10000), iris.data,iris.target, cv = skf, scoring='accuracy')

In [30]:
lr

array([0.89473684, 0.97368421, 0.97297297, 1.        ])

In [31]:
print(f"The mean of the cross_val_score using logistic regression is {np.mean(lr)}.")

The mean of the cross_val_score using logistic regression is 0.960348506401138.


In [32]:
tree = cross_val_score(DecisionTreeClassifier(), iris.data,iris.target, cv = skf, scoring='accuracy')
tree

array([0.94736842, 0.97368421, 0.86486486, 0.91891892])

In [33]:
print(f"The mean of the cross_val_score using decision tree is {np.mean(tree)}.")

The mean of the cross_val_score using decision tree is 0.9262091038406828.


In [34]:
rf = cross_val_score(RandomForestClassifier(), iris.data,iris.target, cv = skf, scoring='accuracy')
rf

array([0.94736842, 0.97368421, 1.        , 0.86486486])

In [35]:
print(f"The mean of the cross_val_score using random forest is {np.mean(rf)}.")

The mean of the cross_val_score using random forest is 0.9464793741109531.


In [36]:
svm = cross_val_score(SVC(), iris.data,iris.target, cv = skf, scoring='accuracy')
svm

array([1.        , 0.92105263, 1.        , 0.97297297])

In [37]:
print(f"The mean of the cross_val_score using svm is {np.mean(svm)}.")

The mean of the cross_val_score using svm is 0.9735064011379801.
